/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Start.java
 *
 * Created on 2010-05-17, 21:58:39
 */

package kik;

import java.awt.Toolkit;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fro
 */
public class Start extends javax.swing.JFrame {

    /** Creates new form Start */
    public Start() {
        initComponents();

        int width = Toolkit.getDefaultToolkit().getScreenSize().width;
        int height = Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setBounds(width/2-164, height/2-105, 328, 210);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartPolacz = new javax.swing.JButton();
        StartZalozSerwer = new javax.swing.JButton();
        StartZakoncz = new javax.swing.JButton();
        label1 = new java.awt.Label();
        GrajPC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PJ Tic Tac Toe");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(java.awt.Color.white);
        setResizable(false);

        StartPolacz.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        StartPolacz.setText("Połącz");
        StartPolacz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStartPolacz(evt);
            }
        });

        StartZalozSerwer.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        StartZalozSerwer.setText("Załóż serwer");
        StartZalozSerwer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStartZalozSerwer(evt);
            }
        });

        StartZakoncz.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        StartZakoncz.setText("Zakończ");
        StartZakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStartZakoncz(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 12));
        label1.setText("Tic Tac Toe / Nazwa Kodowa: Biq Noob");

        GrajPC.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        GrajPC.setText("Graj z PC");
        GrajPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aGrajPC(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GrajPC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(StartZalozSerwer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(StartPolacz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(StartZakoncz, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartPolacz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartZalozSerwer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GrajPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartZakoncz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aStartZakoncz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStartZakoncz
        if (Dialogi.pytanie("Czy na pewno?", "Zakończ program")) {
            System.exit(0);
        }
    }//GEN-LAST:event_aStartZakoncz

    private void aStartZalozSerwer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStartZalozSerwer
        try {
            this.setVisible(false);
            new Serwer();           
        } catch (UnknownHostException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aStartZalozSerwer

    private void aStartPolacz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStartPolacz
        this.setVisible(false);
        new Klient();
    }//GEN-LAST:event_aStartPolacz

    private void aGrajPC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aGrajPC
        this.setVisible(false);
        new PCKlient();
    }//GEN-LAST:event_aGrajPC

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GrajPC;
    private javax.swing.JButton StartPolacz;
    private javax.swing.JButton StartZakoncz;
    private javax.swing.JButton StartZalozSerwer;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}
